workflows:
  openlineage-integration-python:
    jobs:
      - notify-finish:
          context: howard-slack
          requires:
            - workflow_complete
      - unit-test-client-python
      - build-client-python:
          filters:
            branches:
              only: main
          build_tag: ".dev<< pipeline.number >>"
          requires:
            - unit-test-client-python
      - workflow_complete:
          requires:
            - build-client-python
            - unit-test-client-python
